const plotType = {
    basicallyIntactBuildings:{
        name:"基本完好建筑物",
        personnelCasualties:{
            type:"select",
            name:"人员伤亡",
            value:"",
            content:[
                {
                    value:"hasCasualties",
                    lable:"有（10人以上）"
                },
                {
                    value:"noHasCasualties",
                    lable:"无（10人一下）"
                },
            ]
        },
        natureOfUse:{
            type:"select",
            name:"使用性质",
            value:"",
            content:[
                {
                    value:"residentialBuilding",
                    lable:"住宅楼"
                },
                {
                    value:"selfBuiltHouses",
                    lable:"自建房"
                },
                {
                    value:"officeBuilding",
                    lable:"办公楼"
                },
                {
                    value:"school",
                    lable:"学校"
                },
                {
                    value:"hospital",
                    lable:"医院"
                },
                {
                    value:"workshop",
                    lable:"厂房"
                },
                {
                    value:"warehouse",
                    lable:"仓库"
                },
                {
                    value:"gymnasium",
                    lable:"体育馆"
                },
                {
                    value:"exhibitionHall",
                    lable:"展览馆"
                },
                {
                    value:"other",
                    lable:"其它"
                },
            ]
        },
        structureType:{
            type:"select",
            name:"结构类型",
            value:"",
            content:[
                {
                    value:"brickAndWoodStructure",
                    lable:"砖木结构"
                },
                {
                    value:"brickConcreteStructure",
                    lable:"砖混结构"
                },
                {
                    value:"reinforcedConcreteStructure ",
                    lable:"钢筋混凝土结构"
                },
                {
                    value:"steelStructure",
                    lable:"钢结构"
                },
                {
                    value:"other",
                    lable:"其它"
                },
            ]
        },
        damageModel:{
            type:"select",
            name:"破坏模式",
            value:"",
            content:[
                {
                    value:"vibrationDamage",
                    lable:"振动破坏（地面振动通过基础传递到建筑物导致）"
                },
                {
                    value:"foundationFailure",
                    lable:"地基失效破坏（如震后地基不均匀沉降、水平变位等导致）"
                },
                {
                    value:"secondaryEffectDamage",
                    lable:"次生效应破坏（如震后滑坡、崩塌等导致）"
                },
            ]
        },
        disposalTeam:{
            type:"text",
            name:"处置队伍",
            value:""
        },
        disposalMeasures:{
            type:"text",
            name:"处置措施",
            value:""
        },
        disposalPhase:{
            type:"select",
            name:"处置阶段",
            value:"",
            content:[
                {
                    value:"notYetProcessed",
                    lable:"暂未处置"
                },
                {
                    value:"processing",
                    lable:"正在处置"
                },
                {
                    value:"completeDisposal",
                    lable:"完成处置"
                },
            ]
        },
        disposalProcess:{
            type:"partText",
            name:"处置过程",
            value:""
        },
        contactStaff:{
            type:"text",
            name:"联系人员",
            value:""
        },
        contactNumber:{
            type:"text",
            name:"联系电话",
            value:""
        },
    },
}
export {plotType}